;;; funcs.el --- structured writing layer functions file
;;
;; Copyright (c) 2012-2016 Sylvain Benner & Contributors
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;;; Code:

(defun my-org-remove-heading (tags)
  ""
 (org-map-entries (lambda () (delete-region (point-at-bol) (point-at-eol)))
                  (mapconcat 'identity tags "|"))
)

(defun my-org-remove-section (tags)
  ""
  (org-map-entries (lambda () (let ((beg (point)))
                                (outline-next-visible-heading 1)
                                (backward-char)
                                (delete-region beg (point))))
                   (mapconcat 'identity tags "|")
                   tree)
)

(defun my-org-prepare-multi-tag (tag)
  ""
  (show-all)
  (my-org-remove-section (remove tag my-org-tags))
  (my-org-remove-heading '("References" "Appendix"))
)

(defun my-org-prepare-unique-tag (tag)
  ""
  (show-all)
  (my-org-remove-section (remove tag my-org-tags))
  (my-org-remove-heading (cons tag '("References" "Appendix")))
)

(defun my-org-prepare-unique-parental-tag (tag children)
  ""
  (show-all)
  (my-org-remove-section (remove tag my-org-tags))
  (my-org-remove-heading (cons tag '("References" "Appendix")))
  (org-map-entries (lambda () (org-promote)) children)
)

;;; The following functions will be generated by a macro:
;(defun org-enable-prepare-export-structure () (add-hook 'org-export-before-processing-hook #'org-prepare-export-structure))
;(defun org-disable-prepare-export-structure () (remove-hook 'org-export-before-processing-hook #'org-prepare-export-structure))
(defmacro make-my-org-prepare-export-functions (name preparation key)
  `(progn
     (defun ,(intern (format "my-org-prepare-export-%s" name)) (backend)
       ""
       ,preparation
       )
     (defun ,(intern (format "my-org-enable-prepare-export-%s" name))  ()
       (add-hook 'org-export-before-processing-hook
                 #',(intern (format "my-org-prepare-export-%s" name))))
     (defun ,(intern (format "my-org-disable-prepare-export-%s" name)) ()
       (remove-hook 'org-export-before-processing-hook
                    #',(intern (format "my-org-prepare-export-%s" name))))
     (defun ,(intern (format "my-org-latex-publish-to-pdf-%s" name)) (plist filename pub-dir)
       (org-publish-attachment
        plist
        (org-latex-compile
         (org-publish-org-to 'latex
                             filename ,(format ".%s.tex" name)
                             plist (file-name-directory filename)))
        pub-dir))
     (defun ,(intern (format "my-org-publish-%s" name)) ()
       (interactive)
       (let ((name ,name))
       (org-publish
        `(,(concat (file-name-base (buffer-file-name (buffer-base-buffer))) "-" name)
           :base-directory ,(file-name-directory (buffer-file-name (buffer-base-buffer)))
           :base-extension "org"
           :publishing-directory ,(file-name-directory (buffer-file-name (buffer-base-buffer)))
           :preparation-function ,(intern (format "my-org-enable-prepare-export-%s" name))
           :completion-function ,(intern (format "my-org-disable-prepare-export-%s" name))
           :publishing-function ,(intern (format "my-org-latex-publish-to-pdf-%s" name))
           :include (,(file-name-nondirectory (buffer-file-name (buffer-base-buffer))))
           :exclude "\\.org$"
           :latex-class "scrartcl"
           :with-toc nil
           ))))
     (spacemacs/set-leader-keys-for-major-mode 'org-mode
        ,(format "r%s" key) ',(intern (format "my-org-publish-%s" name)))
))

;;; (symbol-function 'my-org-publish-goals)

(defmacro make-two-functions (name)
  `(progn
     (defun ,(intern (format "my-function-a-%s" name)) (a) '("a" "b" (format "1%s2" a)))
))

(make-two-functions "123")
